### ISSUE TITLE
Cropping of images

### ISSUE THREAD

**Issue by g7gpr** [markmac99/RMS#70]
![AU000Z_20230117_115005_397297_track_stack](https://user-images.githubusercontent.com/77130399/213159653-5550b39e-51b1-40ab-a25c-e68e084c9442.jpg)
![AU000Z_20230117_115005_397297_track_stack_cropped edges](https://user-images.githubusercontent.com/77130399/213159659-07689f91-51e8-4e21-9924-5b423ca04341.jpg)

6 co-located cameras, all with same focal length lenses produced these images. The top of the image was cut off with the code in the original condition. I modified one line 

209c209
<     img_size = int(scale*2*ang_sep_max*pp_ref.F_scale)*4
---
>     img_size = int(scale*2*ang_sep_max*pp_ref.F_scale)

With the image size scaled by 4 x the whole image was visible. I understand the code, but I do not know why this fudge factor was required.

**Comment by markmac99** [comment]
is the top image the adjusted one? I'm not sure of the exact problem. 
Could you please create an example dataset, zip it up and upload it to dropbox or similar so that i can test/explore.

**Comment by g7gpr** [comment]
Top image is the adjusted one. 

The zip file at 

https://www.dropbox.com/sh/a3dwiibfwn4mdvd/AAB2Iy0LiBggJsvzbiyhizsca?dl=0

contains a dataset from 6 co-located cameras.

Trackstack1.sh and Trackstack2.sh are the two commands which I used to produce the two images in the directory. 

The outputs 

AU000Z_20230203_114047_390677_track_stack_1.jpg
and
AU000Z_20230203_114047_390677_track_stack_2.jpg

show the effects.

**Comment by markmac99** [comment]
Fixed with PR #73 by adding a -f/--scalefactor parameter. Default value 1, set to 2 or 3 to scale the canvas out.

**Comment by markmac99** [comment]
@g7gpr  when you get a chance can you test the fix please?  In my dev and master branches.

**Comment by g7gpr** [comment]
Tested and working as expected. Thank you; I'll close the issue. 

![AU000Z_20230203_114047_390677_track_stack_3](https://user-images.githubusercontent.com/77130399/216960313-b21af789-d1f0-4e71-82b5-2d4b9984e9e0.jpg)

Updated zip file with the command and output is in the same dropbox location, but probably of no interest now. 

Dave

**Comment by g7gpr** [comment]
I think I see why this fudge is necessary. On single camera, the middle platepar will be somewhere near the centre. On a multiple camera, it could be anywhere.

**Comment by markmac99** [comment]
Yes, exactly. Its probably possible to determine the required canvas size but... :)
